### ISSUE TITLE
Cannot link with Base on OCaml 4.06

### ISSUE THREAD

**Issue by Julow** [ocaml/camlp-streams#4]
On OCaml < 4.06 it seems not possible to link both ocamlp-streams and the stdlib's `Stream` modules at the same time. The stdlib's module can often be a transitive dependency, for example of `base`.

A small ocaml program that links to both this library and base:
```ocaml
let () = Stream.(empty (Stream.of_list (Base.List.join [])))
```
```dune
(executable
 (name test)
 (libraries base camlp-streams))
```

The error looks like this:
```
File "test.ml", line 1:
Error: The files /home/jules/.opam/4.06.1/lib/camlp-streams/stream.cmi
       and /home/jules/.opam/4.06.1/lib/base/base.cmi
       make inconsistent assumptions over interface Stream
```

This happens in `odoc-parser`: https://github.com/ocaml-doc/odoc-parser/pull/6

**Comment by kit-ty-kate** [comment]
Given this package is meant to be a compatibility package, I think it would be worth doing the same thing as with `stdlib-shims` and making the package empty on OCaml < 5.0

**Comment by dra27** [comment]
Something slightly different is wanted for 4.14.0 - if you’ve specified camlp-streams, it seems reasonable that you shouldn’t get the deprecation warning from the stdlib

**Comment by xavierleroy** [comment]
If I understand correctly, there's no problem with OCaml 4 versions that pack Stream as Stdlib.Stream, i.e. 4.07 and later.  So, the package must be empty only on OCaml < 4.07.  And I agree with @dra27 that it must not be empty for 4.14.

**Comment by kit-ty-kate** [comment]
That sounds fair enough indeed

**Comment by c-cube** [comment]
Just want to mention I met the same issue. I hope it gets released soon :)
